### ISSUE TITLE
Información con casi un año sin actualizar

### ISSUE THREAD

**Issue by jakobhans** [phpdevenezuela/php-the-right-way#12]
Esta versión está totalmente fuera de sincronía con la fuente original. Es muy preocupante, especialmente desde que salió PHP7

**Comment by joseayram** [comment]
¡Hola @jakobhans! Ciertamente el proyecto ha estado abandonado por mucho. Intentaremos moverlo de nuevo con toda la colaboración de quienes se sumen, así que: ¡Bienvenido! Saludos.
