### ISSUE TITLE
Traducir: Chapter 2 - Getting Started

### ISSUE THREAD

**Issue by joseayram** [phpdevenezuela/php-the-right-way#15]

**Comment by JMEspiz** [comment]
Feliz noche, quiero colaborar con la traduccion, voy a tomar esta seccion de primeros pasos.
Serian los archivos:
- 01-01-01
- 01-02-01
- 01-03-01
- 01-04-01
- 01-05-01

Y enviare el PR para su revision.

Saludos.

**Comment by talueses** [comment]
Gracias, @JMEspiz estaremos atentos con tus aportes. :+1:

**Comment by JMEspiz** [comment]
Enviado el PR, estare pendiente de sus correciones :+1:  :)

**Comment by joseayram** [comment]
@JMEspiz ¿A dónde fue enviado el PR? No lo veo.
