### ISSUE TITLE
Traducir: Chapter 8 - Databases

### ISSUE THREAD

**Issue by joseayram** [phpdevenezuela/php-the-right-way#21]

**Comment by 3rn3st0** [comment]
Tomo este capítulo, al llegar a casa leeré y empezaré el trabajo.

**Comment by joseayram** [comment]
@3rn3st0 Cuando hagas el commit por favor apunta al issue para tenerlo por acá relacionado  #21

**Comment by joseayram** [comment]
@3rn3st0 @oyepez003 ¿Falta algo acá?
